sudo: false
language: node_js
node_js:
  - 'stable'
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - realpath
script:
  - './build/download.sh'
  - './build/make.sh'
  - 'if [[ ( "$TRAVIS_BRANCH" == "master" ) && ( "$TRAVIS_OS_NAME" == "linux" ) ]]; then ./build/publish-linux.sh; fi'
  - 'if [[ ( "$TRAVIS_BRANCH" == "master" ) && ( "$TRAVIS_OS_NAME" == "osx" ) ]]; then ./build/publish-macos.sh; fi'
notifications:
  email:
    on_success: never
