sudo: false
language: node_js
node_js:
  - 'stable'
addons:
  apt:
    packages:
    - realpath
script:
  - './build/download.sh'
  - './build/make.sh'
  - '[ "$TRAVIS_BRANCH" == "master" ] && ./build/publish-linux.sh' # todo: macos
notifications:
  email:
    on_success: never
