sudo: false
language: node_js
node_js:
  - 'stable'
addons:
  apt:
    packages:
    - realpath
script:
  - './build/download.sh'
  - './build/make.sh'
  - 'npm test'
notifications:
  email:
    on_success: never
