sudo: false
language: node_js
node_js:
  - 'stable'
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - realpath
script:
  - './build/download.sh'
  - './build/make.sh'
  - '[ "$TRAVIS_OS_NAME" == "linux" ] && ./build/publish-linux.sh'
  - '[ "$TRAVIS_OS_NAME" == "osx" ] && ./build/publish-macos.sh'
notifications:
  email:
    on_success: never
