os: Visual Studio 2017
environment:
  nodejs_version: latest
platform:
  - x64
install:
  - npm install
build_script:
  - curl -L -# -o sox.tar.gz https://downloads.sourceforge.net/project/sox/sox/14.4.2/sox-14.4.2.tar.gz
  - tar -x -z -C sox-src --strip-components 1 -f sox.tar.gz
  - cd sox-src
  - configure
  - make -s
# todo: test
after_build:
  - npm i semver --no-save
  - npm version --no-git-tag-version --force $(node_modules\.bin\semver -i minor $(npm info sox-static-macos version))
  - ps: '"//registry.npmjs.org/:_authToken=$env:NPM_KEY`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm publish
