name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  # make this workflow callable from other workflows
  workflow_call:

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-13 # force x64, see https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#standard-github-hosted-runners-for-public-repositories
        node-version:
          - 6.x
          - 8.x
          - 10.x
          - 12.x
          - 14.x
          - 16.x
          - lts/*

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y coreutils

    - name: Download Dependencies
      run: ./build/download.sh

    - name: Build
      run: ./build/make.sh
