name: Build and Publish

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  build:
    name: build
    uses: './.github/workflows/build.yml'

  publish:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js LTS
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y coreutils

    - name: Download Dependencies
      run: ./build/download.sh

    - name: Build
      run: ./build/make.sh

    - name: Publish Linux Package
      if: runner.os == 'Linux'
      run: ./build/publish-linux.sh
      env:
        NPM_KEY: ${{ secrets.NPM_KEY }}

    - name: Publish macOS Package
      if: runner.os == 'macOS'
      run: ./build/publish-macos.sh
      env:
        NPM_KEY: ${{ secrets.NPM_KEY }}
